controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

#aboutMe:
#    path: /aboutMe
#    controller: App\Controller\LearningController::aboutMe